[package]
name = "vex-sys"
version = "0.1.0"
authors = ["Noam Kleinburd <noam93k@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2.60"

[build-dependencies]
fs_extra = "0.1.0"
foreman = "0.4.0"
bindgen = "0.50"
